name: 

on:
  push:
    branches: 
    - "Master"
jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Merge development -> staging
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: Master
        target_branch: Staging
        github_token: ${{ secrets.GITHUBTOKEN }}
