name: CI Build

on:
  push:
    branches: 
    - "Staging"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: setup-MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Restore Nuget packages
      run: nuget restore PAGEDEMO.sln
      
    - name: Build the Solution
      run: msbuild PAGEDEMO.sln
